version: "3.8"
services:
  webapp:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: django/distroless
    container_name: django-distroless
    hostname: django-dev-distroless
    ports: 
      - 8000:8000
    volumes:
       - ./app:/app
    # command: sleep 3600